### ISSUE TITLE
GS1-128 Internal product variant not detected

### ISSUE THREAD

**Issue by MasterPCUK** [jodal/biip#123]
For some reason AI20 is not begin detected

Here's an example, what is begin returned
(01)10884521761599(11)210701(10)21G0073JZ2023

vs what I expect
(01)10884521761599(11)210701(10)21G0073JZ(20)23

Any advice would be helpful.

**Comment by jodal** [comment]
If you check the official AI list or https://github.com/jodal/biip/blob/main/src/biip/gs1/_application_identifiers.json#L30 you'll see that AI 10 is variable length. That means that unless it is the last AI in the string, it must be terminated by a FNC1 character.

FNC1 is a real symbol when the data is encoded as e.g. a GS1-128 barcode, but once you scan the barcode, what character you get in that position, if any, depends upon the barcode scanner's configuration.

You can read more about this in the docs at https://biip.readthedocs.io/en/stable/quickstart/#variable-length-fields

**Comment by jodal** [comment]
If you or your employer are using Biip, I'd love it if you add yourself to https://github.com/jodal/biip/wiki/Users :-)
