### ISSUE TITLE
Extract GCP

### ISSUE THREAD

**Issue by stereobooster** [jodal/biip#160]
Hi. Thanks for the project. 

apparently it is possible to extract GCP from GTIN (even if it is variable length). Here is another library which does it https://github.com/enorganic/gtin/blob/master/scripts/update_gcp_prefix_format_list.py

Any chance to add this feature to your library?

**Comment by jodal** [comment]
Thanks! If you're using Biip, I'd appreciate if you added your company or yourself to the [lists of users](https://github.com/jodal/biip/wiki/Users)!

Biip currently only supports getting the GS1 member organization prefix, indicating what country the GTIN was issued in: https://biip.readthedocs.io/en/stable/api/gtin/#biip.gtin.Gtin.prefix

I was not aware of the company prefix length [data set](https://www.gs1.org/docs/gcp_length/gcpprefixformatlist.xml)'s existence, but this looks like a very interesting addition to Biip. I'll probably have a go at adding it to an upcoming Biip 3.0 release soon.

**Comment by stereobooster** [comment]
For now I just do some experiments with it, as soon as I start using it I will update the list

**Comment by stereobooster** [comment]
Maybe this would be interesting for you. Just found that there is official (GS1) C library https://github.com/gs1/gs1-syntax-engine

**Comment by jodal** [comment]
[Biip 3.0.0](https://github.com/jodal/biip/releases/tag/v3.0.0) have now been released. It includes the changes discussed here, hopefully making Biip useful in your use case.

**Comment by stereobooster** [comment]
Oh wow. That was fast
