### ISSUE TITLE
ISBT Support

### ISSUE THREAD

**Issue by Tim-Jackins** [jodal/biip#82]
Is there a plan to add ISBT barcodes to the list of supported standards? If you don't plan on adding this do you have any pointers on implementation?

**Comment by jodal** [comment]
I'm not familiar with ISBT, but after searching around I found the specification at http://www.iccbba.org/tech-library/iccbba-documents/standards-documents, which I assume is what you're referring to?

It looks like an interesting case to implement. However, page two of the specification includes the following copyright notice:

![screenshot_2021-05-11_23-43-39](https://user-images.githubusercontent.com/43726/117889200-6d71d980-b2b3-11eb-8787-9ccb7b9fa3a2.png)

My reading of the copyright notice is that it is not allowed to make implementations of ISBT without having a license from ICCBBA. If my interpretation is correct, ISBT is probably not a candidate for inclusion in Biip.
