### ISSUE TITLE
Any plan to cover other GS1 AIs like GLN, GRAI, etc?

### ISSUE THREAD

**Issue by dizhu1991** [jodal/biip#91]
Feel the package will do much more good if it supports other common AIs such as GLN, GRAI, GINC, GSIN, etc.

**Comment by jodal** [comment]
What use cases are you thinking of? Biip already support extracting any AI from GS1 Element Strings. The only thing I think could be added with explicit support for these formats would be checksum checking of e.g. GLNs.

**Comment by jodal** [comment]
Biip [v2.1.0](https://github.com/jodal/biip/releases/tag/v2.1.0) includes GLN parsing and validation. I'll close this issue until I hear some demand and use cases for the other AIs mentioned here.
