### ISSUE TITLE
EAN-13 edge cases

### ISSUE THREAD

**Issue by bbeniamin** [jodal/biip#93]
I noticed that some EAN-13 barcodes cannot be parsed, even though they seem to be in use. 
For example, `biip` cannot find a valid GS1 prefix for 6712670000276 (according to the list [here](https://www.gs1.org/standards/id-keys/company-prefix), 671 indeed doesn't seem to be used yet), but I can find [a product](https://www.barcodelookup.com/6712670000276) associated with this barcode.
Is this barcode an edge case that is still unhandled by `biip`? Any ideas on how this could be fixed?
cc @c-w

**Comment by jodal** [comment]
I think I'd like Biip to be able to parse the GTIN and verify the checksum even if the  prefix hasn't been assigned by GS1.

That change will require a couple of small but breaking API changes, so it'll be a 2.0 release. I have another potentially breaking change coming up too, so I'd like to research and fix that at the same time, hopefully within a couple of weeks.

**Comment by jodal** [comment]
The fix for this is in the `main` branch now. I'll hold off on a release until I've figured out the other issue I want to include in a slightly API-breaking 2.0 release. Feel free to give the Git version a go and let me know if it solves your issue.

**Comment by jodal** [comment]
I've shipped Biip 2.0.0 including the fix for this bug now. Remember to add yourself to the [users list](https://github.com/jodal/biip/wiki/Users) if you end up using Biip :-)
